### PR TITLE
[CLI] Fix butteraugli for auto-optimizer

### LINKED ISSUE #898: [CLI] No effect from --optimizer-butteraugli-target flag.
**Describe the bug**

When running WebP compression with the CLI, I'm getting identical output (and pretty aggressive compression) regardless of the chosen `--optimizer-butteraugli-target` flag. I'm currently using that flag as my main way of tuning quality, and it seemed to work OK in v0.3.1, but in v0.6.0 it has no effect in my tests. 

**To Reproduce**
1. Input:  

<details>
<summary>Avocado.png</summary>

Avocado

</details>

2. Compress with `squoosh-cli --webp "{}" --optimizer-butteraugli-target 1.4 --max-optimizer-rounds 6 --output-dir ~/Desktop ~/Desktop/Avocado.png`
3. Compress with `squoosh-cli --webp "{}" --optimizer-butteraugli-target 0.0001 --max-optimizer-rounds 6 --output-dir ~/Desktop ~/Desktop/Avocado.png`
4. Output is identical (visually and in size) and significantly lower quality than the original.

[Archive.zip](https://github.com/GoogleChromeLabs/squoosh/files/5670545/Archive.zip)

**Expected behavior**

Low values of `--optimizer-butteraugli-target` should produce greater quality and lower compression.

**Version:**
 - OS w/ version: macOS 10.15.7
 - Node version: v14.14.0
 - npm version: v6.14.8

**Is your issue related to the quality of image compression?**

[Archive.zip](https://github.com/GoogleChromeLabs/squoosh/files/5670553/Archive.zip)

### PR DESCRIPTION
**Pull request by surma**
Probably closes #898

### CODE REVIEW

File: codecs/visdif/visdif.cpp [hunk 1]
```diff
@@ -22,10 +22,10 @@ void planarize(std::vector<ImageF>& img,
     float* const row_b = img[2].Row(y);
     float* const row_a = img[3].Row(y);
     for (int x = 0; x < width; x++) {
-      row_r[x] = 255.0 * pow(rgba[y * width * 4 + x * 4 + 0] / 255.0, gamma);
-      row_g[x] = 255.0 * pow(rgba[y * width * 4 + x * 4 + 1] / 255.0, gamma);
-      row_b[x] = 255.0 * pow(rgba[y * width * 4 + x * 4 + 2] / 255.0, gamma);
-      row_a[x] = 255.0 * pow(rgba[y * width * 4 + x * 4 + 3] / 255.0, gamma);
+      row_r[x] = 255.0 * pow((uint8_t)rgba[(y * width + x) * 4 + 0] / 255.0, gamma);
```
Comment (RReverser) [inline codecs/visdif/visdif.cpp]: A better fix would be to change the param itself to `const uint8_t *rgba` IMO.

**Review by RReverser — APPROVED** [review]
