### PR TITLE
fix broken file renaming for file names with dot

### LINKED ISSUE #154: File renaming broken if name includes .
Seems like we trim after the first `.`. It should be the last.

### PR DESCRIPTION
**Pull request by sendilkumarn**
fixes #154

### CODE REVIEW

File: src/components/App/index.tsx [hunk 1]
```diff
@@ -107,7 +107,7 @@ async function compressImage(
 
   return new File(
     [compressedData],
-    sourceFilename.replace(/\..+$/, '.' + encoder.extension),
+    sourceFilename.replace(/.([^.]*)$/, `.${encoder.extension}`),
```
Comment (mathiasbynens) [inline src/components/App/index.tsx]: Since we don't need to capture the group here, let's avoid capturing: `/.(?:[^.]*)$/`

In fact, we don't need the group at all: `/.[^.]*$/`

Comment (sendilkumarn) [reply src/components/App/index.tsx]: Good catch @mathiasbynens I am sending in a fix now
