### PR TITLE
Site isolation headers & redirect fix

### LINKED ISSUE #852: Use correct origin trial on live build
We need to use a different header on live than dev. Make this happen.

### PR DESCRIPTION
**Pull request by jakearchibald**
Fixes #852

### CODE REVIEW

File: src/static-build/utils.tsx [hunk 1]
```diff
@@ -56,3 +56,16 @@ export function escapeStyleScriptContent(str: string): string {
     .replace(/<style/g, '<\\style')
     .replace(/<\/style/g, '<\\/style');
 }
+
+/**
+ * Removes empty lines from start and end, and removes the initial indent from
```
Comment (RReverser) [inline src/static-build/utils.tsx]: I probably would have used `dedent` from npm to avoid dealing with getting regexes right, but maybe it's not worth it for something still fairly small :)

Comment (jakearchibald) [reply src/static-build/utils.tsx]: Done! I wasn't aware of dedent.

**Review by RReverser — APPROVED** [review]
LGTM. I wish we could keep config options separate from code, but I don't see a good way to do that and it probably doesn't matter as much anyway.

**Comment by jakearchibald** [comment]
I was going to create a build step that creates these from ejs templates, but it seemed to make more sense to use the templating system we had, rather than add another one.
